export const mainTheme = {
  token: { fontFamily: "noto-sans-bengali" },
  components: {
    Form: {
      colorError: "#E53935",
    },
    Checkbox: {
      colorPrimary: "#273D62",
      colorPrimaryHover: "#273D62",
    },
    Modal: {
      zIndexBase: 999999,
      titleFontSize: 25,
    },
    Select: {
      // colorTextQuaternary: "#ffffff",
      colorBgContainer: "rgba(0,0,0,0)",
      fontSize: 18,
      optionSelectedColor: "#ffffff",
      optionSelectedBg: "#589283",
      optionActiveBg: "#58928355",
      optionActiveColor: "#efefef",
      colorBorder: "#efefef",
      colorBgElevated: "#efefef",
      selectorBg: "#F3F3F5",
      colorText: "#262621",
      colorTextPlaceholder: "#5d5d5d",
      // activeOutlineColor: "#5d5d5d",
      // activeBorderColor: "#5d5d5d",
      hoverBorderColor: "#5d5d5d",
    },
    DatePicker: {
      fontSize: 20,
      colorBorder: "rgb(0, 0, 0,0.5)",
      colorTextPlaceholder: "rgb(0, 0, 0,0.5)",
    },
    Upload: {
      colorFillAlter: "rgba(0,0,0,0)",
      colorBorder: "#D3EBE7",
      colorBorderHover: "#D3EBE7",
      colorText: "#D3EBE7",
    },
    Table: {
      headerBg: "#b8c1c355",
      colorBgContainer: "#FDFDFD",
      colorText: "#262621",
      borderColor: "#DFE1E3",
      headerColor: "#262621",
      fontSize: 18,
      footerColor: "#FDFDFD",
      // marginXXS: 4,
      colorLinkActive: "#FDFDFD",
      headerSplitColor: "#262621",
    },
    Pagination: {
      itemActiveBg: "#273D62",
      colorPrimary: "#F3F3F3",
      colorPrimaryHover: "#F3F3F3",
    },
    Input: {
      colorTextPlaceholder: "#D0D5DD ",
      colorIcon: "#D0D5DD",
    },
  },
};
